### ISSUE TITLE
Node fails to load

### ISSUE THREAD

**Issue by ShadoW-Shinigami** [glibsonoran/Plush-for-ComfyUI#64]
Here is the log
```Plush - Running on python installation: /home/ubuntu/miniconda3/envs/comfy/bin/python, ver: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]
Plush - Current Openai Version:  1.12.0
Traceback (most recent call last):
  File "/home/ubuntu/repos/comfy/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/repos/comfy/custom_nodes/Plush-for-ComfyUI/__init__.py", line 13, in <module>
    jmanager = json_manager()
  File "/home/ubuntu/repos/comfy/custom_nodes/Plush-for-ComfyUI/mng_json.py", line 157, in __init__
    self.customnodes_dir = self.find_child_directory(self.comfy_dir, 'custom_nodes', False, True)
  File "/home/ubuntu/repos/comfy/custom_nodes/Plush-for-ComfyUI/mng_json.py", line 408, in find_child_directory
    parent_path = Path(parent)
  File "/home/ubuntu/miniconda3/envs/comfy/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/home/ubuntu/miniconda3/envs/comfy/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/ubuntu/miniconda3/envs/comfy/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Cannot import /home/ubuntu/repos/comfy/custom_nodes/Plush-for-ComfyUI module for custom nodes: expected str, bytes or os.PathLike object, not NoneType```

**Comment by glibsonoran** [comment]
Did you make your own directory structure for the ComfyUI installation or is this just the standard Linux installation directory structure?  The suite is expecting: .../ComfUI/custom_nodes/Plush-for-ComfyUI but your installation appears to be: ...comfy/custom_nodes/Plush-forComfyUI.

I don't have a Linux computer at home, so I'm just trying to understand if this issue is unique to your installation, or if it's a difference in how the directories are structure for Linux vs Windows &  Mac.

**Comment by glibsonoran** [comment]
OK, try cloning the repo again (or you can just upload and replace: `style_prompt.py & mng_json.py` if you don't want to do the whole clone).  This should fix your problem, but let me know if it doesn't.

I'd still like to know if this is the standard Linux directory structure.

Thx
