### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by imperator-maximus** [glibsonoran/Plush-for-ComfyUI#71]
Hello,

it is not loading for me. I a getting:

> Traceback (most recent call last):
  File "E:\sd\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\SD\ComfyUI\custom_nodes\Plush-for-ComfyUI\__init__.py", line 5, in <module>
    from .mng_json import json_manager
  File "E:\SD\ComfyUI\custom_nodes\Plush-for-ComfyUI\mng_json.py", line 147, in <module>
    class json_manager:
  File "E:\SD\ComfyUI\custom_nodes\Plush-for-ComfyUI\mng_json.py", line 499, in json_manager
    def read_lines_of_file(self, file_path: Union[str, Path], lines:int=0, is_critical: bool = False) -> list|None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Thank you

**Comment by glibsonoran** [comment]
The code that's causing the problem is using a type hint that only works for Python versions 3.10 or higher.  Also, there are many other nodes and add-ons of ComfyUI that aren't going to work well with pre 3.10 Python.  To future proof, I suggest upgrade your Python to 3.10.9 or 3.11.

**Comment by imperator-maximus** [comment]
thank you very much. Yes there was one other node not working as well. So it works fine now after Python upgrade.
